image: node:12

stages:
  - check
  - build
  - test
  - deploy

Audit:
  stage: check
  before_script:
    - npm ci
  script:
    - npm audit

Static Test:
  stage: check
  before_script:
    - npm ci
  script:
    - npm run test:code

Build:
  stage: build
  before_script:
    - npm ci
    - npm i -g copyfiles
  script:
    - npm run build
    - npm run postbuild

Deploy (NPM):
  stage: deploy
  dependencies:
    - Build
  only:
    - master
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm ci
    - npm i -g copyfiles
    - npm run build
    - npm run postbuild
    - npm publish
