image: node:12

stages:
  - check
  - build
  - test
  - deploy

Audit:
  stage: check
  before_script:
    - npm ci
  script:
    - npm audit

Static test:
  stage: check
  before_script:
    - npm ci
  script:
    - npm run test:code

Build:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build

Unit Test:
  stage: test
  allow_failure: false
  before_script:
    - npm ci
  script:
    - npm run test:app

Deploy (NPM):
  stage: deploy
  dependencies:
    - Unit Test
  only:
    - master
  before_script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - npm ci
    - npm run build
  script:
    - npm publish
